# -*- coding: utf-8 -*-
"""ManhattanModelBig.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/120YBS3ArwyNvbYOmCH3uviY2bJk839He
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd

data1 = '/content/drive/MyDrive/Manhattan/weather/Data/base_data.csv'
data2 = '/content/drive/MyDrive/Manhattan/weather/Data2/'

import os
# Initialize an empty dictionary to store the DataFrames
geohash_dfs = {}

# Loop through the files in the directory
for filename in os.listdir(data2):
    if filename.endswith(".csv"):
        # Extract the geohash from the filename (assuming the filename is in the format 'geohash.csv')
        geohash = filename.split('.')[0]

        # Load the CSV file into a DataFrame
        df = pd.read_csv(os.path.join(data2, filename))

        # Add the DataFrame to the dictionary
        geohash_dfs[geohash] = df

# Verify the loaded DataFrames
for geohash, df in geohash_dfs.items():
    print(f"Geohash: {geohash}")
    print(df.head())  # Display the first few rows of each DataFrame
    print("\n")

test_df = geohash_dfs['dr5rus'].copy()

trialdf = test_df[['OFFER_DATE','time_of_day','day_of_week','month','temperature','precipitation']]

dr5rus_df = trialdf.copy()

dr5rus_df = dr5rus_df.sort_values(by='OFFER_DATE')

# Convert 'OFFER_DATE' to datetime objects
dr5rus_df['OFFER_DATE'] = pd.to_datetime(dr5rus_df['OFFER_DATE'])

# Shift the OFFER_DATE column to create the next ride's time
dr5rus_df['next_OFFER_DATE'] = dr5rus_df['OFFER_DATE'].shift(-1)

# Calculate the time difference to the next ride
dr5rus_df['time_to_next_ride'] = (dr5rus_df['next_OFFER_DATE'] - dr5rus_df['OFFER_DATE']).dt.total_seconds()

# Drop the temporary column next_OFFER_DATE
dr5rus_df.drop(columns=['next_OFFER_DATE'], inplace=True)

dr5rus_df.dropna(subset=['time_to_next_ride'])

dr5rus_df.dropna(subset=['time_to_next_ride'], inplace=True)

import holidays
us_holidays = holidays.US()

# Step 2: Create the 'is_holiday' feature
dr5rus_df['is_holiday'] = dr5rus_df['OFFER_DATE'].dt.date.apply(lambda x: 1 if x in us_holidays else 0)

dr5rus_df

original_size = len(merged_df)

# Filter out rows where 'time_to_next_ride' is greater than 2000 seconds
filtered_df = merged_df[merged_df['time_to_next_ride'] <= 1500]

# Calculate the new size of the dataset
filtered_size = len(filtered_df)

# Calculate the percentage of data removed
percentage_removed = ((original_size - filtered_size) / original_size) * 100

print(f"Original dataset size: {original_size} rows")
print(f"Filtered dataset size: {filtered_size} rows")
print(f"Percentage of data removed: {percentage_removed:.2f}%")

percentile_98 = filtered_df['time_to_next_ride'].quantile(0.98)

# Filter the DataFrame to remove the top 2% of outliers
filtered_df_no_outliers = filtered_df[filtered_df['time_to_next_ride'] <= percentile_98]

# Calculate the percentage of data removed
percentage_removed = (len(filtered_df) - len(filtered_df_no_outliers)) / len(filtered_df) * 100

print(f"98th percentile value: {percentile_98}")
print(f"Original dataset size: {len(filtered_df)} rows")
print(f"Filtered dataset size: {len(filtered_df_no_outliers)} rows")
print(f"Percentage of data removed: {percentage_removed:.2f}%")

import matplotlib.pyplot as plt
import seaborn as sns

# Assume filtered_df is your DataFrame after filtering

# Plot the histogram of 'time_to_next_ride'
plt.figure(figsize=(12, 6))
sns.histplot(filtered_df['time_to_next_ride'], bins=50, kde=True, color='blue')
plt.xlabel('Time to Next Ride (s)')
plt.ylabel('Frequency')
plt.title('Distribution of Time to Next Rides')
plt.show()

df = filtered_df.copy()

fft = tf.signal.rfft(df['time_to_next_ride'])
f_per_dataset = np.arange(0, len(fft))

n_samples_h = len(df['time_to_next_ride'])
hours_per_year = 24*365.2524
years_per_dataset = n_samples_h/(hours_per_year)

f_per_year = f_per_dataset/years_per_dataset
plt.step(f_per_year, np.abs(fft))
plt.xscale('log')
plt.ylim(0, 6000000)
plt.xlim([0.1, max(plt.xlim())])
plt.xticks([1, 365.2524], labels=['1/Year', '1/day'])
_ = plt.xlabel('Frequency (log scale)')

df.describe().transpose()

dr5rus_df = filtered_df.copy()

dr5rus_df

dr5rus_df.to_csv('/content/drive/MyDrive/Manhattan/weather/dr5rus_test4.csv', index=False)

import numpy as np
import pandas as pd
import tensorflow as tf
from sklearn.preprocessing import MinMaxScaler
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense
from sklearn.model_selection import train_test_split

# Select the features and target
features = dr5rus_df[['time_of_day', 'day_of_week', 'month','temperature','precipitation','is_holiday']]
target = dr5rus_df['time_to_next_ride']

# Normalize the features
feature_scaler = MinMaxScaler()
features_scaled = feature_scaler.fit_transform(features)
print(features_scaled)

# Normalize the target
target_scaler = MinMaxScaler()
target_scaled = target_scaler.fit_transform(target.values.reshape(-1, 1))

# Reshape the data to fit the LSTM input requirements
time_steps = 1  # Since each row is a separate time step
X = features_scaled
# X = np.reshape(features_scaled, (features_scaled.shape[0], time_steps, features_scaled.shape[1]))
y = target_scaled

print("Preprocessed data shape:", X.shape)
print("Target shape:", y.shape)

# Split the data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print("Training data shape:", X_train.shape)
print("Testing data shape:", X_test.shape)

model = Sequential()
model.add(Dense(units=128, activation='relu', input_shape = (features_scaled.shape[1],))) # Pass input_shape as a tuple
model.add(Dense(units=32, activation='relu'))
model.add(Dense(units=16, activation='relu'))
model.add(Dense(units=1, activation='sigmoid'))

# Print the model summary
model.summary()
model.compile(optimizer='adam', loss='mse')

# Train the model
history = model.fit(X_train, y_train, epochs=100, batch_size=32, validation_split=0.2, verbose=1)

# Evaluate the model
loss = model.evaluate(X_test, y_test, verbose=1)
print(f'Test Loss: {loss}')

# Make predictions
predictions = model.predict(X_test)

# Inverse transform the predictions and the true values to get them back to the original scale
predictions_inverse = target_scaler.inverse_transform(predictions)
y_test_inverse = target_scaler.inverse_transform(y_test.reshape(-1, 1))

print("Predictions (first 10):", predictions_inverse[:10])
print("True values (first 10):", y_test_inverse[:10])

mask = y_test_inverse.flatten() <= 2000

# Filtered true values and predictions
y_test_filtered = y_test_inverse[mask]
predictions_filtered = predictions_inverse[mask]

# Calculate the percentage of rides removed
total_rides = len(y_test_inverse)
filtered_rides = len(y_test_filtered)
rides_removed = total_rides - filtered_rides
percentage_removed = (rides_removed / total_rides) * 100

print(f"Percentage of rides removed: {percentage_removed:.2f}%")
percentage_error = np.abs((y_test_filtered - predictions_filtered) / y_test_filtered) * 100

import matplotlib.pyplot as plt

def plot_filtered_results(sample_size, plot_type='line', marker_color='blue', marker_size=10):
    # Ensure the sample size is not greater than the filtered data size
    sample_size = min(sample_size, len(y_test_filtered))

    plt.figure(figsize=(20, 15))
    if plot_type == 'line':
        plt.plot(y_test_filtered[:sample_size], label='True Values', linestyle='-', linewidth = marker_size)
        plt.plot(predictions_filtered[:sample_size], label='Predictions', linestyle='-', linewidth = marker_size)
    elif plot_type == 'scatter':
        plt.scatter(range(sample_size), y_test_filtered[:sample_size], label='True Values', c='blue', s=marker_size)
        plt.scatter(range(sample_size), predictions_filtered[:sample_size], label='Predictions', c=marker_color, s=marker_size)
    plt.legend()
    plt.xlabel('Sample Index')
    plt.ylabel('Time to Next Ride (s)')
    plt.title(f'True Values vs. Predictions (Filtered, <= 2000, Sample Size: {sample_size})')
    plt.show()

    # Plot percentage error
    plt.figure(figsize=(20, 15))
    if plot_type == 'line':
        plt.plot(percentage_error[:sample_size], label='Percentage Error', linestyle='-', linewidth = marker_size)
    elif plot_type == 'scatter':
        plt.scatter(range(sample_size), percentage_error[:sample_size], label='Percentage Error', c=marker_color, s=marker_size)
    plt.legend()
    plt.xlabel('Sample Index')
    plt.ylabel('Percentage Error (%)')
    plt.title(f'Percentage Error (Filtered, <= 2000, Sample Size: {sample_size})')
    plt.show()

plot_filtered_results(2000, plot_type='line', marker_color='red', marker_size=1)

model.save('/content/drive/MyDrive/Manhattan/weather/models/dr5rustuner1-holiday.keras')
print("Model saved successfully.")