# -*- coding: utf-8 -*-
"""modelevaluation-lowermanhattan.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VBhgZ0q7k7wivc9R5Wrx4shNH6AZiArP
"""

from google.colab import drive
drive.mount('/content/drive')

import os
import pandas as pd
import holidays
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
import tensorflow as tf

data2 = '/content/drive/MyDrive/Manhattan/weather/Data2/'

geohash_dfs = {}

for filename in os.listdir(data2):
    if filename.endswith(".csv"):
        geohash = filename.split('.')[0]

        df = pd.read_csv(os.path.join(data2, filename))

        geohash_dfs[geohash] = df

# Verify the loaded DataFrames
for geohash, df in geohash_dfs.items():
    print(f"Geohash: {geohash}")
    print(df.head())
    print("\n")

def preprocess_data(df):
    trialdf = df[['OFFER_DATE', 'time_of_day', 'day_of_week', 'month', 'temperature', 'precipitation']]

    trialdf = trialdf.sort_values(by='OFFER_DATE')

    trialdf['OFFER_DATE'] = pd.to_datetime(trialdf['OFFER_DATE'])

    trialdf['next_OFFER_DATE'] = trialdf['OFFER_DATE'].shift(-1)

    trialdf['time_to_next_ride'] = (trialdf['next_OFFER_DATE'] - trialdf['OFFER_DATE']).dt.total_seconds()

    trialdf.drop(columns=['next_OFFER_DATE'], inplace=True)

    trialdf.dropna(subset=['time_to_next_ride'], inplace=True)

    us_holidays = holidays.US()
    trialdf['is_holiday'] = trialdf['OFFER_DATE'].dt.date.apply(lambda x: 1 if x in us_holidays else 0)

    filtered_df = trialdf.copy()

    return filtered_df

filtered_dfs = {}
for geohash, df in geohash_dfs.items():
    filtered_df = preprocess_data(df)
    filtered_dfs[geohash] = filtered_df
    print(f"Geohash: {geohash}")
    print(filtered_df.head())
    print("\n")

filtered_dfs.keys()

def traintestsplit(df):
    # Select the features and target
    features = df[['time_of_day', 'day_of_week', 'month', 'temperature', 'precipitation', 'is_holiday']]
    target = df['time_to_next_ride']

    # Normalize the features
    feature_scaler = MinMaxScaler()
    features_scaled = feature_scaler.fit_transform(features)

    # Normalize the target
    target_scaler = MinMaxScaler()
    target_scaled = target_scaler.fit_transform(target.values.reshape(-1, 1))

    # Split the data
    X_train, X_test, y_train, y_test = train_test_split(features_scaled, target_scaled, test_size=0.2, random_state=12)
    test_data = (X_test, y_test)
    return test_data,target_scaler

test_data ={}
for geohash, df in filtered_dfs.items():
    test, targer_scaler = traintestsplit(df)
    test_data[geohash] = (test, target_scaler)
    print(f"Geohash: {geohash}")
    print(test_data[geohash])
    print("\n")

for geohash, (test, target_scaler) in test_data.items():
    print(f"Geohash: {geohash}")
    print(test[0],test[1], target_scaler)
    print("\n")

model_dir = '/content/drive/MyDrive/Manhattan/weather/models/'

def predict_model(geohash, X_test, y_test, target_scaler):
  model_path = os.path.join(model_dir, f"{geohash}_model.keras")
  model = tf.keras.models.load_model(model_path)
  predictions = model.predict(X_test.reshape(1, X_test.shape[0], X_test.shape[1]))
  predictions_inverse = target_scaler.inverse_transform(predictions)
  y_test_inverse = target_scaler.inverse_transform(y_test.reshape(-1, 1))
  predicted_val = predictions_inverse, y_test_inverse
  return predicted_val

predicted_val = {}
for geohash, (test, target_scaler) in test_data.items():
    predicted_val[geohash] = predict_model(geohash, test[0], test[1], target_scaler)
    print(f"Geohash: {geohash}")
    print(predicted_val)
    print("\n")